### ISSUE TITLE
Plain output is converted/casted to other formats

### ISSUE THREAD

**Issue by foolioo** [TomWright/dasel#294] opened 2023-02-04 09:13 UTC
**Describe the bug**
When using a [plain output](https://daseldocs.tomwright.me/supported-file-formats), dasel converts the values and does not display them as plain, which also affects the selection of values.

For instance, integer values are being converted to exponent notation.

**To Reproduce**

```shell
$ echo '[4090849286]' | dasel -r json -w - '.all()'
4.090849286e+09

$ echo '[4090849286]' | dasel -r json '.all()'
4090849286

$ echo '{"foo": "bar"}' | dasel -r json ".filter(equal(foo,bar))"
{
  "foo": "bar"
}

$ echo '{"foo": 12345678}' | dasel -r json ".filter(equal(foo,12345678))"

$ echo '{"foo": 12345678}' | dasel -r json ".filter(equal(foo,1.2345678e+07))"
{
  "foo": 12345678
}
```

**Expected behavior**

dasel should not convert the values to any type and keep them as is so plain output and selection/filtration will work as expected.

**Desktop (please complete the following information):**

- OS: Linux/MacOS
- Version: 2.1.1

Relates to #245, #293

**Comment by TomWright** [comment] 2023-02-07 14:42
This issue is caused by the fact that all comparisons are string comparisons.

The best way to solve this is to allow functions to accept arguments of different types.

The given example causes a comparison on the following types, which is obviously false since they are strings.

```
12345678.000000 string, 12345678 string
```

**Comment by TomWright** [comment] 2023-05-15 22:58
FYI This has been merged to master and is available in the development version. This will be included in the next relase.

**Closed by TomWright** 2023-05-15 22:58 UTC
Labels: bug
