### ISSUE TITLE
-w xml is not working when -r is not xml

### ISSUE THREAD

**Issue by piotrwiniarczyk-silvair** [TomWright/dasel#354] opened 2023-08-30 15:09 UTC
**Describe the bug**
The -w xml option is producing strange output. There is no way to convert from json/yaml to xml, while the opposite is possible. Manipulating input xml is possible.

**To Reproduce**
Try this:
`echo '<t>A</t>' | dasel -r xml -w xml`
vs
`echo '<t>A</t>' | dasel -r xml -w json | dasel -r json -w xml`

There is no problem to convert from json to json via yaml, etc.

**Expected behavior**
-w xml should produce a valid xml when `-r` value is not xml.

**Desktop (please complete the following information):**

Windows 11, 64bit, git-bash 
dasel version v2.3.4

**Comment by TomWright** [comment] 2023-08-30 15:17
Hey @piotrwiniarczyk-silvair , thanks for raising this.

I can confirm there is something wrong:
```
$ echo 'x: y
a: b' | dasel -r yaml -w xml
&{[x a] map[a:b x:y]}
```

It looks like I've missed a step when converting to XML from the internal OrderedMap type.

**Comment by TomWright** [comment] 2023-08-30 15:33
Release has been made and will be available under brew etc soon. Closing this issue as the problem has been resolved.

**Closed by TomWright** 2023-08-30 15:33 UTC
Labels: bug
